import { MigrationInterface, QueryRunner } from "typeorm";

export class AddUserNameField1779083076168 implements MigrationInterface {
    name = 'AddUserNameField1779083076168'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "joint_work" DROP CONSTRAINT "FK_0b5c5f724eb1db04e069abf1a10"`);
        await queryRunner.query(`ALTER TABLE "sessions" DROP CONSTRAINT "FK_7f37c20c6ad759dfe747d2a4f08"`);
        await queryRunner.query(`ALTER TABLE "feedback" DROP CONSTRAINT "FK_d7a67472ee670fbc4b83955d27f"`);
        await queryRunner.query(`ALTER TABLE "samples" DROP CONSTRAINT "FK_41f7b900f44127da4b74f567b82"`);
        await queryRunner.query(`ALTER TABLE "workplace" DROP CONSTRAINT "FK_7a5202710160e4f375d52464f27"`);
        await queryRunner.query(`ALTER TABLE "rcpa" DROP CONSTRAINT "FK_e74093853ff1d969ebb9419c05a"`);
        await queryRunner.query(`ALTER TABLE "gifts" DROP CONSTRAINT "FK_b7be409c6018094eda3edd2015e"`);
        await queryRunner.query(`ALTER TABLE "users" DROP CONSTRAINT "FK_cd9740f36970d326b3f65bd5e99"`);
        await queryRunner.query(`ALTER TABLE "holidays" DROP CONSTRAINT "FK_6f41d8c3e40558745c1a53b9327"`);
        await queryRunner.query(`ALTER TABLE "new_target" DROP CONSTRAINT "FK_e5837e258b3b3d0e6fe00cf5550"`);
        await queryRunner.query(`DROP INDEX "public"."UQ_object_field_definitions_object_field"`);
        await queryRunner.query(`DROP INDEX "public"."UQ_object_record_type_definitions_object_name"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "availability"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "user_type_id"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "dob"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "role"`);
        await queryRunner.query(`DROP TYPE "public"."users_role_enum"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "address"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "is_deleted"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "age"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "value_target"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "learning_role"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "store_target"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "orgName"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "image"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "patient_volume"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "zone"`);
        await queryRunner.query(`ALTER TABLE "users" ADD "middlename" character varying(100)`);
        await queryRunner.query(`ALTER TABLE "users" ADD "name" character varying(255)`);
        await queryRunner.query(`ALTER TABLE "users" ADD "username" character varying(100)`);
        await queryRunner.query(`ALTER TABLE "users" ADD CONSTRAINT "UQ_fe0bb3f6520ee0469504521e710" UNIQUE ("username")`);
        await queryRunner.query(`ALTER TABLE "users" ADD "nickname" character varying(100)`);
        await queryRunner.query(`ALTER TABLE "users" ADD "active" boolean NOT NULL DEFAULT true`);
        await queryRunner.query(`ALTER TABLE "users" ADD "country" character varying(100)`);
        await queryRunner.query(`ALTER TABLE "users" ADD "region" character varying(100)`);
        await queryRunner.query(`ALTER TABLE "users" ADD "street" text`);
        await queryRunner.query(`ALTER TABLE "users" ADD "mobile" character varying(20)`);
        await queryRunner.query(`ALTER TABLE "users" ADD "department" character varying(100)`);
        await queryRunner.query(`ALTER TABLE "users" ADD "division" character varying(100)`);
        await queryRunner.query(`ALTER TABLE "users" ADD "team" character varying(100)`);
        await queryRunner.query(`ALTER TABLE "users" ADD "vertical" character varying(100)`);
        await queryRunner.query(`ALTER TABLE "users" ADD "title" character varying(100)`);
        await queryRunner.query(`ALTER TABLE "users" ADD "language" character varying(100)`);
        await queryRunner.query(`ALTER TABLE "users" ADD "timeZone" character varying(100)`);
        await queryRunner.query(`ALTER TABLE "users" ADD "employeeId" character varying(100)`);
        await queryRunner.query(`ALTER TABLE "users" ADD CONSTRAINT "UQ_a7191f881489123fab6c8e52738" UNIQUE ("employeeId")`);
        await queryRunner.query(`ALTER TABLE "users" ADD "resignationDate" date`);
        await queryRunner.query(`ALTER TABLE "users" ADD "delegatedApproverId" integer`);
        await queryRunner.query(`ALTER TABLE "users" ADD "roleId" integer`);
        await queryRunner.query(`ALTER TABLE "users" ADD "isDeleted" boolean NOT NULL DEFAULT false`);
        await queryRunner.query(`ALTER TABLE "users" ADD "managerId" integer`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "firstname"`);
        await queryRunner.query(`ALTER TABLE "users" ADD "firstname" character varying(100) `);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "lastname"`);
        await queryRunner.query(`ALTER TABLE "users" ADD "lastname" character varying(100) `);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "password"`);
        await queryRunner.query(`ALTER TABLE "users" ADD "password" character varying(255) `);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "state"`);
        await queryRunner.query(`ALTER TABLE "users" ADD "state" character varying(100)`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "phone"`);
        await queryRunner.query(`ALTER TABLE "users" ADD "phone" character varying(20)`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "joining_date"`);
        await queryRunner.query(`ALTER TABLE "users" ADD "joining_date" date`);
        await queryRunner.query(`ALTER TABLE "users" ADD CONSTRAINT "FK_874662e039ab7d31a71450eb501" FOREIGN KEY ("managerId") REFERENCES "users"("emp_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "users" ADD CONSTRAINT "FK_4f92d9988cb43cdd546bcb4b1a8" FOREIGN KEY ("delegatedApproverId") REFERENCES "users"("emp_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "users" DROP CONSTRAINT "FK_4f92d9988cb43cdd546bcb4b1a8"`);
        await queryRunner.query(`ALTER TABLE "users" DROP CONSTRAINT "FK_874662e039ab7d31a71450eb501"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "joining_date"`);
        await queryRunner.query(`ALTER TABLE "users" ADD "joining_date" TIMESTAMP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "phone"`);
        await queryRunner.query(`ALTER TABLE "users" ADD "phone" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "state"`);
        await queryRunner.query(`ALTER TABLE "users" ADD "state" character varying`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "password"`);
        await queryRunner.query(`ALTER TABLE "users" ADD "password" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "lastname"`);
        await queryRunner.query(`ALTER TABLE "users" ADD "lastname" character varying`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "firstname"`);
        await queryRunner.query(`ALTER TABLE "users" ADD "firstname" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "managerId"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "isDeleted"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "roleId"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "delegatedApproverId"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "resignationDate"`);
        await queryRunner.query(`ALTER TABLE "users" DROP CONSTRAINT "UQ_a7191f881489123fab6c8e52738"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "employeeId"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "timeZone"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "language"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "title"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "vertical"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "team"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "division"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "department"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "mobile"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "street"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "region"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "country"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "active"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "nickname"`);
        await queryRunner.query(`ALTER TABLE "users" DROP CONSTRAINT "UQ_fe0bb3f6520ee0469504521e710"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "username"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "name"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "middlename"`);
        await queryRunner.query(`ALTER TABLE "users" ADD "zone" character varying`);
        await queryRunner.query(`ALTER TABLE "users" ADD "patient_volume" integer`);
        await queryRunner.query(`ALTER TABLE "users" ADD "image" character varying`);
        await queryRunner.query(`ALTER TABLE "users" ADD "orgName" character varying`);
        await queryRunner.query(`ALTER TABLE "users" ADD "store_target" integer`);
        await queryRunner.query(`ALTER TABLE "users" ADD "learning_role" character varying`);
        await queryRunner.query(`ALTER TABLE "users" ADD "value_target" integer`);
        await queryRunner.query(`ALTER TABLE "users" ADD "age" integer`);
        await queryRunner.query(`ALTER TABLE "users" ADD "is_deleted" boolean NOT NULL DEFAULT false`);
        await queryRunner.query(`ALTER TABLE "users" ADD "address" character varying`);
        await queryRunner.query(`CREATE TYPE "public"."users_role_enum" AS ENUM('ADMIN', 'DIRECTOR', 'RSM', 'ASM', 'SO', 'SSM', 'MANAGER', 'DISTRIBUTOR', 'RETAILER', 'SUPER_ADMIN', 'CHANNEL')`);
        await queryRunner.query(`ALTER TABLE "users" ADD "role" "public"."users_role_enum" NOT NULL DEFAULT 'SSM'`);
        await queryRunner.query(`ALTER TABLE "users" ADD "dob" TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "users" ADD "user_type_id" integer`);
        await queryRunner.query(`ALTER TABLE "users" ADD "availability" integer`);
        await queryRunner.query(`CREATE UNIQUE INDEX "UQ_object_record_type_definitions_object_name" ON "object_record_type_definitions" ("objectId", "recordTypeName") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "UQ_object_field_definitions_object_field" ON "object_field_definitions" ("fieldName", "objectId") `);
        await queryRunner.query(`ALTER TABLE "new_target" ADD CONSTRAINT "FK_e5837e258b3b3d0e6fe00cf5550" FOREIGN KEY ("emp_id") REFERENCES "users"("emp_id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "holidays" ADD CONSTRAINT "FK_6f41d8c3e40558745c1a53b9327" FOREIGN KEY ("added_by") REFERENCES "users"("emp_id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "users" ADD CONSTRAINT "FK_cd9740f36970d326b3f65bd5e99" FOREIGN KEY ("user_type_id") REFERENCES "user_types"("user_type_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "gifts" ADD CONSTRAINT "FK_b7be409c6018094eda3edd2015e" FOREIGN KEY ("added_by") REFERENCES "users"("emp_id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "rcpa" ADD CONSTRAINT "FK_e74093853ff1d969ebb9419c05a" FOREIGN KEY ("added_by") REFERENCES "users"("emp_id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "workplace" ADD CONSTRAINT "FK_7a5202710160e4f375d52464f27" FOREIGN KEY ("added_by") REFERENCES "users"("emp_id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "samples" ADD CONSTRAINT "FK_41f7b900f44127da4b74f567b82" FOREIGN KEY ("added_by") REFERENCES "users"("emp_id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "feedback" ADD CONSTRAINT "FK_d7a67472ee670fbc4b83955d27f" FOREIGN KEY ("added_by") REFERENCES "users"("emp_id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "sessions" ADD CONSTRAINT "FK_7f37c20c6ad759dfe747d2a4f08" FOREIGN KEY ("added_by") REFERENCES "users"("emp_id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "joint_work" ADD CONSTRAINT "FK_0b5c5f724eb1db04e069abf1a10" FOREIGN KEY ("emp_id") REFERENCES "users"("emp_id") ON DELETE CASCADE ON UPDATE NO ACTION`);
    }

}
